export default [
    {
        "id": 1,
        "filename": "img1.jpg",
        "category": "headshot"
    }, {
        "id": 2,
        "filename": "img2.jpg",
        "category": "headshot"
    }, {
        "id": 3,
        "filename": "img3.jpg",
        "category": "headshot"
    }, {
        "id": 4,
        "filename": "img4.jpg",
        "category": "headshot"
    }, {
        "id": 5,
        "filename": "img5.jpg",
        "category": "headshot"
    }, {
        "id": 6,
        "filename": "img6.jpg",
        "category": "headshot"
    }, {
        "id": 7,
        "filename": "img7.jpg",
        "category": "headshot"
    }, {
        "id": 8,
        "filename": "img8.jpg",
        "category": "headshot"
    }, {
        "id": 9,
        "filename": "img9.jpg",
        "category": "film"
    }, {
        "id": 10,
        "filename": "img10.jpg",
        "category": "film"
    }, {
        "id": 11,
        "filename": "img11.jpg",
        "category": "film"
    }, {
        "id": 12,
        "filename": "img12.jpg",
        "category": "film"
    }, {
        "id": 13,
        "filename": "img13.jpg",
        "category": "improv"
    }, {
        "id": 14,
        "filename": "img14.jpg",
        "category": "improv"
    }, {
        "id": 15,
        "filename": "img15.jpg",
        "category": "improv"
    }, {
        "id": 16,
        "filename": "img16.jpg",
        "category": "redcarpet"
    }, {
        "id": 17,
        "filename": "img17.jpg",
        "category": "redcarpet"
    }, {
        "id": 18,
        "filename": "img18.jpg",
        "category": "redcarpet"
    }, {
        "id": 19,
        "filename": "img19.jpg",
        "category": "redcarpet"
    }, {
        "id": 20,
        "filename": "img20.jpg",
        "category": "redcarpet"
    }, {
        "id": 21,
        "filename": "img21.jpg",
        "category": "redcarpet"
    }, {
        "id": 22,
        "filename": "img22.jpg",
        "category": "theater"
    }, {
        "id": 23,
        "filename": "img23.jpg",
        "category": "theater"
    }, {
        "id": 24,
        "filename": "img24.jpg",
        "category": "theater"
    }, {
        "id": 25,
        "filename": "img25.jpg",
        "category": "theater"
    }, {
        "id": 26,
        "filename": "img26.jpg",
        "category": "theater"
    }, {
        "id": 27,
        "filename": "img27.jpg",
        "category": "theater"
    }, {
        "id": 28,
        "filename": "img28.jpg",
        "category": "theater"
    }, {
        "id": 29,
        "filename": "img29.jpg",
        "category": "theater"
    }, {
        "id": 30,
        "filename": "img30.jpg",
        "category": "theater"
    }, {
        "id": 31,
        "filename": "img31.jpg",
        "category": "theater"
    }
]

